name: personal_blog
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.2
  shelf_static: ^1.1.3
  shelf_router: ^1.1.4
  postgres: ^3.5.6
  dargon2: ^3.2.1 # Replace 'argon2' with this
  jaguar_jwt: ^3.0.0
  path: ^1.9.1
  mustache_template: ^2.0.0
  markdown: ^7.0.0

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^5.0.0
